dev

- let the dev script user know what's going on 
Not a single one.

Dev script tweaks

---

broker/huey_consumer.py
broker/tasks/cloudfront.py
broker/tasks/db_injection.py
broker/tasks/finalize.py
broker/tasks/iam.py
broker/tasks/letsencrypt.py
broker/tasks/route53.py
docker/serve
tests/integration/test_provisioning.py

- inject app sessions into Huey tasks
- replace print statements with logs in several places
- set up cf_logging for consumers
None

give huey access to app sessions

---

acceptance/run.sh
ci/pipeline.yml

-  use random domains for tests
None

use random domains for testing

---

broker/aws.py
broker/config.py
broker/tasks/iam.py
tests/conftest.py
tests/integration/alb/test_alb_deprovisioning.py
tests/integration/alb/test_alb_provisioning.py
tests/integration/cdn/test_cdn_deprovisioning.py
tests/integration/cdn/test_cdn_provisioning.py
tests/lib/fake_iam.py
tests/unit/test_config.py

- split commercial and govcloud IAM resources
None

split commercial and govcloud IAM resources

---

broker/config.py
tests/integration/alb/test_alb_deprovisioning.py
tests/integration/alb/test_alb_provisioning.py
tests/integration/cdn/test_cdn_deprovisioning.py
tests/integration/cdn/test_cdn_provisioning.py
tests/lib/fake_alb.py
tests/lib/fake_iam.py
tests/unit/test_config.py

refactor alb tests and test libraries to prep for other changes

---

broker/tasks/alb.py
broker/tasks/pipelines.py
tests/integration/alb/test_alb_provisioning.py
tests/lib/fake_alb.py

- use lowest-utilized alb when provisioning
None

select lowest-utilized ALB

---

ci/pipeline.yml

- add production pipeline
None

add prod to pipeline

---

broker/tasks/alb.py
tests/lib/fake_alb.py

- Don't set isDefault, since AWS apparently doesn't want to know
None

don't set isDefault

---

acceptance/run.sh
ci/pipeline.yml

- use multiple test domains
None

add config for multiple test domains

---

broker/tasks/cloudfront.py
broker/tasks/pipelines.py
tests/integration/cdn/test_cdn_renewals.py
tests/lib/fake_cloudfront.py

- add renewals for CDN instances
None

renew CDN instance certificates

---

broker/tasks/pipelines.py
tests/integration/alb/test_alb_renewals.py
tests/integration/cdn/test_cdn_renewals.py

add renewals for ALBs

---

acceptance/run.sh
broker/api.py
broker/models.py
broker/tasks/cloudfront.py
tests/integration/cdn/test_cdn_provisioning.py
tests/integration/test_bind.py
tests/integration/test_server_setup.py
tests/lib/fake_cloudfront.py

- add support for cookie filtering
- import pytest for all integration tests to make pytest.mark.skip and pytest.mark.focus work correctly 
None

add support for cookie filtering

---

broker/api.py
broker/models.py
broker/tasks/huey.py
migrations/versions/e1793cdca02f_backfill_cdn_updates.py
tests/integration/cdn/test_cdn_provisioning.py
tests/integration/test_failing_tasks.py
tests/lib/fake_cloudfront.py
tests/lib/tasks.py

- mark operations as failed when a pipeline fails
None

Task failures

---

broker/tasks/cron.py
tests/integration/test_stalled_operations.py

-  add function to look for stalled pipelines
None

add function to look for stalled pipelines

---

broker/tasks/cloudfront.py
tests/integration/test_cloudfront_idempotency.py

fixes #120
- create CloudFront distributions idempotently
None

idempotent creation of cloudfront distributions

---

broker/tasks/letsencrypt.py
tests/integration/test_letsencrypt_idempotent.py

- fixes #118
- make LE steps idempotent
None

make Lets Encrypt steps idempotent

---

broker/tasks/iam.py
tests/integration/test_bind.py
tests/integration/test_iam_idempotent.py
tests/lib/fake_iam.py

-  make IAM functions idempotent, kinda fixes #122 
None

idempotentish iam functions

---

broker/tasks/cron.py

- add periodic task to restart failed pipelines
fixes #86 
fixes #37 
[Note the any security considerations here, or make note of why there are none]

add periodic task to restart stalled pipelines

---

broker/tasks/alb.py
broker/tasks/cron.py
broker/tasks/route53.py
tests/integration/test_loadbalancer_idempotent.py
tests/lib/fake_route53.py

- add IPv6 support to route53 operations
fixes #111 
None

add IPv6 CNAMEs

---

broker/config.py
broker/tasks/cron.py

-  Bail on cron tasks if not configured to run them
None

abandon cron tasks on all but one instance

---

broker/api.py
broker/models.py
broker/tasks/cloudfront.py
broker/tasks/letsencrypt.py
broker/tasks/pipelines.py
broker/tasks/route53.py
broker/tasks/update_operations.py
broker/validators.py
tests/integration/alb/test_alb_provisioning.py
tests/integration/alb/test_alb_update.py
tests/integration/cdn/test_cdn_provisioning.py
tests/integration/cdn/test_cdn_renewals.py
tests/integration/cdn/test_cdn_update.py
tests/lib/client.py

- support updating service instances
None

Support updates

---

ci/pipeline.yml

add slack alerts to deployments

---

docs/architecture.md
docs/operational.md
docs/test_layout_and_architecture.md
tests/unit/test_broker_lifecycle.py

- add more docs
- remove some no-op tests
None

add more docs

---

broker/tasks/cron.py

- re-enqueue stalled update pipelines 
closes #146 
none

re-enqueue update pipelines, too

---

acceptance/run.sh
broker/api.py
broker/models.py
broker/tasks/cloudfront.py
tests/integration/cdn/test_cdn_provisioning.py
tests/integration/cdn/test_cdn_update.py
tests/lib/factories.py
tests/lib/fake_cloudfront.py

- Add support for custom error responses in cloudfront
Fixes #148 
None

Custom 404

---

broker/app.py
broker/tasks/cloudfront.py
tests/lib/client.py
tests/lib/fake_cloudfront.py

- don't expose error message to users
None

Quieter errors

---

broker/tasks/route53.py

- Iterate over certificates, so we remove all txt records, and silently pass over the condition where there's only a new_certificate
None

clean up txt records better when canceling instance that is provisioning

---

broker/tasks/cron.py
tests/integration/alb/test_alb_renewals.py
tests/integration/cdn/test_cdn_renewals.py

-  renew certs 30 days out instead of 10
None

Thirty day renewal

---

broker/tasks/pipelines.py

- Refactor the redundant `correlation_id=correlation_id` signatures out so black tidies these lines up nicely
None

refactor correlation_id to tidy up function calls

---

broker/models.py
broker/tasks/cloudfront.py
broker/tasks/cron.py
broker/tasks/pipelines.py
tests/integration/cdn/test_cdn_broker_migration.py
tests/lib/fake_cloudfront.py

- refactor stalled pipeline job 
- add pipeline for migrating from cdn-broker
None

pipeline for migrations from cdn-broker

---

broker/api.py
broker/models.py
tests/integration/migration/test_migration_provisioning.py
tests/lib/client.py
tests/unit/test_broker_lifecycle.py

- Add a MigrationServiceInstance class and a provisioning path for it
- refactor CDN provisioning a tiny bit to make the switch statement on plans a little easier to follow
None

add MigrationServiceInstance class

---

pip-tools/dev-requirements.txt
pip-tools/requirements.in
requirements.txt

- pin cryptography for security issue
Fixes security issue
replaces #187

pin cryptography for security issue

---

broker/tasks/pipelines.py
tests/integration/cdn/test_cdn_update.py

- add missing route53 updates to cdn update
- remove duplicate cdn update pipeline
None

add missing route53 updates to cdn update

---

ci/upgrade-schema.sh

-  use supported health check type
None

use supported health-check-type

---

broker/tasks/letsencrypt.py

- make logging more helpful when certs fail
None

Error messages for acme

---

ci/upgrade-schema.sh

- Update run-task command to cf7 parameters
None

make cf run-task command cf7-compatible

---

broker/validators.py
tests/integration/cdn/test_cdn_update.py
tests/unit/test_cname_validator.py

fixes #195
- allow arbitrary-depth of CNAMEs
None

allow arbitrary-depth of CNAMEs

---

pip-tools/dev-requirements.txt
pip-tools/requirements.in
requirements.txt

- This bumps Jinja to fix a vuln. We're not actually using jinja, so the vuln isn't applicable to us, but dependabot was bugging me about it
pip-tools changed its formatting, too, which makes it look like everything got bumped, but most deps didn't change.
Fixes a theoretical vuln, but doesn't actually apply to us

bump jinja (and others) to fix Jinja vuln

---

broker/api.py
broker/validators.py
tests/unit/test_hostname_validator.py

- add validation for origins
None

add validation for origins

---

broker/api.py
broker/tasks/pipelines.py
tests/integration/migration/test_migration_update_to_cdn.py

fixes #201
- add necessary ALIAS steps for CDN migration
None

add necessary ALIAS steps for CDN migration

---

pip-tools/dev-requirements.txt
pip-tools/requirements.in
requirements.txt

- bump cryptography
Fixes vuln

bump cryptography

---

broker/tasks/cloudfront.py
broker/tasks/pipelines.py
tests/integration/migration/test_migration_update_to_cdn.py
tests/lib/fake_cloudfront.py

- add logging when we migrate a cdn instance
Improves our ability to diagnose issues and attacks

add logging steps to migration pipeline

---

broker/config.py
tests/unit/test_config.py

- fit postgres uri to sqlalchemys expectations
None

fit postgres uri to sqlalchemy's expectations

---

broker/tasks/letsencrypt.py

- add more logs about why cert fetching fails
None

add more logging for failed cert renewals

---

docker/Dockerfile.dev

- update pg install for bullseye (new Debian version)
None

update pg install for bullseye

---

pip-tools/dev-requirements.txt
requirements.txt

- bump versions
addresses urllib alert from dependabot. Replaces #208 and #209

version bumps

---

ci/pipeline.yml

- add all the environments
None

add all the environments

---

ci/pipeline.yml

add creds in

---

broker/api.py
broker/config.py
ci/pipeline.yml
tests/integration/alb/test_alb_provisioning.py
tests/unit/test_config.py

- ignore duplicate domains in special environments
None

ignore duplicate domains in special environments

---

docs/operational.md

- update operational docs with guidance on how to safely run UPDATE queries in a transaction
None

update operational docs with guidance on  UPDATE queries

---

ci/pipeline.yml

- fix error in pipeline definition
None

fix pipeline def

---

ci/pipeline.yml

- Fix pipeline
- Add pipeline groups
None

Fix pipeline

---

broker/config.py
broker/duplicate_certs.py
tests/unit/test_config.py

- fix config loading for upgrade-schema env
- 
- 
none

fix config loading for upgrade-schema env

---

ci/check-duplicate-certs.sh
ci/remove-duplicate-certs.sh
ci/upgrade-schema.sh

- remove set -x statements from bash scripts
These changes improve security and reduce risk of leaking secure values

remove set -x statements from bash scripts

---

broker/duplicate_certs.py

See title
None; logging change to task that runs in CI.

Log exception when deleting certificates

---

broker/duplicate_certs.py

See title
None; see previous pr

Fix syntax error

---

ci/pipeline.yml

- Add back missing gateway value in CI job to remove duplicate certs
n/a

adding in missing gateway value for remove dups job

---

ci/pipeline.yml

- Update to uses external CF Resource and others
This is an improvement since we are switching to hardened resources

Update to uses external CF Resource and others

---

ci/check-duplicate-certs.yml
ci/pipeline.yml
ci/remove-duplicate-certs.yml
ci/stop-apps.yml
ci/upgrade-schema.yml

- update pipeline to use hardened images
Improving security by ensuring that pipeline uses hardened images

update pipeline to use hardened images

---

pip-tools/requirements.in

- remove irrelevant comments - I forgot to clear these out when updating requirements
None - just tidying comments

remove irrelevant comments

---

acceptance/run.sh
ci/pipeline.yml

- update pipeline and acceptance tests for dedicated plans
None

update pipeline and acceptance tests for dedicated plans

---

ci/pipeline.yml

correct parameter name

---

.pre-commit-config.yaml
broker/api.py
broker/app.py
broker/aws.py
broker/config.py
broker/huey_consumer.py
broker/models.py
broker/tasks/alb.py
broker/tasks/cloudfront.py
broker/tasks/cron.py
broker/tasks/letsencrypt.py
broker/tasks/route53.py
broker/tasks/update_operations.py

- add pre-commit for flake8, black, and file fixers
- do linting from new linters
None

Add linters

---

broker/config.py

- add required field to upgrade config
None

add required field to upgrade config

---

broker/api.py

allow updating plans

---

.pre-commit-config.yaml
ci/pipeline.yml

- fix plan visibility for production
- drop check-yaml pre-commit since it doesn't understand our anchors
None

fix plan visibility for production

---

pip-tools/dev-requirements.txt
requirements.txt

- bump dependencies
newer versions have fewer CVEs

bump dependencies

---

ci/pipeline.yml
pip-tools/dev-requirements.txt
requirements.txt

- [upgrade to certifi>=2024.07.04](https://github.com/cloud-gov/external-domain-broker/commit/ae89f337cc92fc74151b593fbebf7f361e0c902f)
- Fix issue with Credhub variables in pipeline definition
PR addresses open security issues identified by Dependabot

Fix pipeline and address security issue

---

broker/config.py

- add missing config property
None

add missing config property

---

ci/pipeline.yml
docker/Dockerfile.dev

- Updates dockerfile to use our hardened base image
- Updates pipeline to use the hardened testing image
Updating code to use hardened image

Harden image

---

broker/tasks/alb.py
broker/tasks/cloudwatch.py
broker/tasks/iam.py
broker/tasks/waf.py
tests/integration/alb/test_alb_renewals.py
tests/integration/test_cloudwatch.py
tests/integration/test_iam_idempotent.py
tests/integration/test_waf.py
tests/lib/fake_cloudwatch.py
tests/lib/fake_iam.py
tests/lib/fake_wafv2.py
tests/lib/update.py

- Make tags optional for creating WAF web ACL
- Make tags optional for creating health check alarms
- Handle deletion failures where certificates may already have been deleted by checking to see if the certificate exists before deleting
None, just addressing observed bugs in the logs

Miscellaneous fixes

---

broker/duplicate_certs.py
tests/integration/alb/test_alb_remove_duplicate_certs.py
tests/integration/dedicated_alb/test_dedicated_alb_remove_duplicate_certs.py

- check for cert before deleting instead of relying on ignoring a failure we won't get 
-
-
None

fix: improve cert cleanup for certs that are not in iam

---

.github/workflows/security-considerations.yml

- Limit permissions to security considerations workflow
Limiting permissions for security considerations workflow follows the principle of least privilege

limit permissions for security considerations workflow
