- .flake8
- pyproject.toml
- Get ready to paint it black
None
> add pyproject.toml for easier black usage, update flake8 to match

- broker/tasks/route53.py
- tests/lib/fake_route53.py
fixes #119
-  use UPSERT to update route53 records
None
> use UPSERT rather than create for Route53 changes

- broker/tasks/alb.py
- tests/integration/test_loadbalancer_idempotent.py
- tests/lib/client.py
- don't pick a new alb on a provision operation where one has already been selected
None
> make alb steps more idempotentish

- broker/tasks/cloudfront.py
- tests/integration/cdn/test_cdn_deprovisioning.py
- get the distribution again in the delete step so we have a fresh ETag
None
> freshen ETag in cloudfront delete step

- broker/api.py
- tests/integration/alb/test_alb_provisioning.py
- tests/integration/alb/test_alb_update.py
-  when the domains are the same and the instance type is ALB, don't do anything on update
None
> don't update ALBs when nothing has changed

- broker/api.py
- broker/config.py
- broker/models.py
- broker/tasks/pipelines.py
- docker/start-servers.sh
- tests/integration/alb/test_alb_provisioning.py
- tests/integration/cdn/test_cdn_provisioning.py
- tests/integration/cdn/test_cdn_update.py
- refactor update and provisioning logic for CDN to prep for no-op checks and to share more logic
- disable random nonce-rejection from pebble test server. The thinking here is that we have sufficient retries in production, but the way we retry in production isn't reflected in our local tests, so injecting the failures into local testing just makes tests flaky
None
> Refactor cdn update parsing

- broker/api.py
- broker/tasks/iam.py
- tests/integration/cdn/test_cdn_provisioning.py
- tests/integration/cdn/test_cdn_update.py
- tests/integration/test_iam_idempotent.py
- Skip certificate updates when there's no change in domains
I think I'm going to skip the rest of the no-op work for now, because:
- it doesn't seem to add a ton of value (calling update on a cloudfront instance is free and not rate-limited)
- it would take quite a bit to test
- being able to issue an update that is theoretically no-op seems potentially useful in the future
closes #149 
None
> skip all the certificate work if the domain names haven't changed

- broker/config.py
- broker/tasks/cloudfront.py
- broker/tasks/cron.py
- ci/pipeline.yml
- tests/integration/cdn/test_cdn_provisioning.py
- tests/integration/cdn/test_cdn_renewals.py
- tests/integration/cdn/test_cdn_update.py
- tests/integration/test_cloudfront_idempotency.py
- tests/lib/fake_cloudfront.py
- tests/unit/test_config.py
fixes #135
- Add logging to cdn distributions
depends on cloud-gov/cg-provision#770
None
> add logging to cloudfront distributions

- broker/tasks/iam.py
- tests/integration/alb/test_alb_deprovisioning.py
- tests/integration/cdn/test_cdn_deprovisioning.py
fixes #138
- Delete both the new and current certificate when deprovisioning. This catches a case where someone deprovisions while provisioning, updating, or renewing, after uploading the server certificate but before updating the CDN or ALB
None
> delete new and current certificate when cleaning up

- broker/tasks/cloudfront.py
- tests/integration/cdn/test_cdn_provisioning.py
- tests/integration/cdn/test_cdn_update.py
- tests/lib/fake_cloudfront.py
- fixes #164 
- CloudFront needs us to pass an ResponseCode along with a ResponsePagePath for CustomErrorResponses
None
> fix CustomErrorResponse config

- broker/api.py
- broker/validators.py
- tests/unit/test_error_response_validator.py
- tests/unit/test_header_validation.py
- Add validator for headers
- Add validator for error_response
I'm copying the existing pattern of validator classes. I don't think it's at all necessary, especially for these simple validations, but the pattern is here, so why re-invent?
None
> add header and error response validation

- broker/tasks/cloudfront.py
- tests/integration/test_cloudfront_idempotency.py
- when we don't have a distribution id, we shouldn't try to operate on a distribution
None
> skip cloudfront steps when no distribution

- broker/tasks/pipelines.py
- tests/integration/alb/test_alb_renewals.py
- tests/integration/cdn/test_cdn_renewals.py
This is not strictly required by Let's Encrypt, but it's best practice
and the get challenges step was modified to assume it was done when the
update logic was added.
- Call the generate CSR step for renewals
None
> get a new csr for renewals

- broker/acme_client.py
- broker/tasks/letsencrypt.py
- tests/integration/alb/test_alb_order_status_mismatch.py
- This adds some error handling to get a certificate in cases where we have already called finalize but don't have the certificate for some reason. You can see the code I borrowed [here](https://github.com/certbot/certbot/blob/f743dbec3a04349533735a161b650f02844b2294/acme/acme/client.py#L737-L767) - basically, we do the last half of this function.
None
> Add errorhandling for orders already finalized

- broker/config.py
- broker/tasks/alb.py
- broker/tasks/iam.py
Right now, when we create a new ALB instance, we almost always get a failure when we go to add the certificate to the ALB, since IAM takes some time for consistency. This means that the task fails, then waits ten minutes before retrying. This tries to work around that by sleeping for 30 seconds after uploading an IAM certificate, only when working with ALB instances. 30 seconds is totally arbitrary.
The same thing happens when we delete a certificate - the first try fails because IAM thinks the ALB is still using it.
This could mean a 19 minute speedup in the alb portion of the smoke tests, which is currently the longer one at about 30 minutes.
-  Add some sleep time after uploading a certificate and after removing one.
None
> add some sleep time 

- broker/tasks/update_operations.py
- instead of canceling provision operations, cancel anything that is not a deprovision operation. These were equivalent when this function was written, but are not anymore since we have update and renewal operations now.
None
> cancel updates and renewals, too

- broker/tasks/huey.py
- remove the `task signal received` logs, as they're never helpful
None
> skip task signal logs

- broker/api.py
- tests/unit/test_provision.py
- We've had a few users bitten by this - arrays are the obvious choice for the domain parameter, but we went with comma-separated strings initially to be consistent with the old brokers. This change allows either
None
> Allow arrays for domains parameter

- broker/api.py
- broker/models.py
- tests/integration/migration/test_migration_provisioning.py
- tests/integration/test_plan_changes.py
- tests/lib/client.py
- tests/lib/factories.py
This is a little clumsy because, as far as I can tell, sqlalchemy won't
let us just directly convert a model type.
- add framework for updating service instance type
None
> add framework for updating service instance type

- docs/operational.md
- Update ops docs Renewal action string to "Renew" and not "Renewal"
None
> Update renewal action name to "Renew"

- broker/tasks/cron.py
- tests/integration/test_stalled_operations.py
- don't pass context id to renewal tasks
Note
> don't pass context id to renewal tasks

- broker/api.py
- broker/models.py
- broker/tasks/pipelines.py
- tests/integration/migration/test_migration_update_to_alb.py
- tests/integration/test_plan_changes.py
- tests/integration/test_stalled_operations.py
- Add pipeline for migrator -> alb updates
- Change validators to allow updating migrator -> alb
- Add API steps to prep migrator for update to alb
- fixes #210 
None
> Allow updating migrator instances to alb instances

- broker/tasks/letsencrypt.py
- tests/integration/alb/test_alb_renewals.py
- tests/integration/test_failing_tasks.py
- clean up new_certificate when retrieval fails due to validation errors. When a validation fails, we need a new order and new challenges in order to retry. Because of this, we need to delete the service_instance.new_certificate record, so we don't try to reuse it
None
> clean up new_certificate when retrieval fails due to validation errors

- broker/tasks/alb.py
- Wait until we've determined there's a cert to remove before we sleep. The sleep here is so we don't remove the cert until the DNS updates have propagated. 
None
> sleep after we've determined we're not skipping the task

- ci/pipeline.yml
- separate service-name from services so we can enable individual services. This way, we can disable visibility on the migration plan
None
> set service visibility correctly

- tests/integration/alb/test_alb_provisioning.py
- tests/integration/cdn/test_cdn_provisioning.py
- reset config value at the end of the test
- add the test for CDNs too
- reset config value at the end of the test
- add the test for CDNs too
None
> Fix cdn provision tests

- pip-tools/requirements.in
- requirements.txt
- git:// is blocked so using https:// for github.com
None
> git:// no longer useable

- broker/duplicate_certs.py
- tests/integration/alb/test_alb_remove_duplicate_certs.py
...so run it on the Certificate object instead.
See: https://stackoverflow.com/questions/19243964/sqlalchemy-delete-doesnt-cascade
None; see previous PR.
> Cascade does not apply to deletes on query objects

- broker/duplicate_certs.py
- tests/integration/alb/test_alb_remove_duplicate_certs.py
- tests/lib/fake_iam.py
- Add logic to delete IAM server certificates
- Update logic to handle case of certificate with no listener ARN
None
> Update remove duplicate cert logic

- broker/duplicate_certs.py
- tests/integration/alb/test_alb_check_duplicate_certs.py
- tests/integration/alb/test_alb_remove_duplicate_certs.py
- tests/lib/fake_alb.py
- Update metric name for duplicate certs to `service_instance_duplicate_cert_count` to clarify that it is a count of duplicate certificates for a service, not all certificates for a service. There should be a total of `service_instance_duplicate_cert_count` + 1 (current certificate) certificates for a service
- Update logic for removing certificates from load balancer listeners to wait for the certificate to no longer be listed in the certificates for that listener. This fixes a bug I observed in the removal where attempting to delete the certificate itself immediately after removing it from the listener failed because the removal from the listener hadn't fully propagated through AWS
None
> Update metric name and certificate removal logic

- ci/check-duplicate-certs.sh
The metric name for duplicate certs per service changed so we need to update the script that greps for that metric in the app output and pushes it to Prometheus
None
> fix ci script to look for correct metric

- acceptance/run.sh
- docker/Dockerfile.dev
- Update Dockerfile installation of PostgreSQL to fix broken ci TASK
- Update acceptance tests to use datestamp for test resources for easier tracking
None
> Fix broken CI

- broker/api.py
- tests/integration/dedicated_alb/test_dedicated_alb_deprovisioning.py
- allow deprovisioning domain-with-org-lb instances (N.B, the tests are identical to the alb tests, except for the types)
None
> allow deprovisioning domain-with-org-lb instances

- broker/models.py
- tests/integration/test_plan_changes.py
- simplify logic on service instance type changes
None - just refactoring
> refactor update checks and logic

- migrations/alembic.ini
- migrations/env.py
- migrations/script.py.mako
- regenerate alembic stuff for sqlalchemy2
None
> regenerate alembic stuff for sqlalchemy2

- dev
- docker/tests
- pyproject.toml
- move ptw config to `pyproject.toml`
- avoid including the host virtualenv in the container mounts so ptw performs slightly better
-
None
> make tests run a little less slowly

- migrations/alembic.ini
- migrations/env.py
- drop bad logger directive 
- switch engine order to avoid throwing warnings
None
> drop bad logger directive, switch engine order 

- ci/pipeline.yml
- set token back to the thing I already set it to ?
None
> set token back to the thing I already set it to ?

- docker/tests
- pip-tools/dev-requirements.txt
- pip-tools/requirements.in
- pyproject.toml
- requirements.txt
- remove pins on some acme, pyopenssl, and cryptography to get latest versions
- add pytest config to suppress deprecation warning (this is what the upstream does, too)
This lets us bump some versions with known security issues
> Remove pins and ignore deprecation warning

- ci/pipeline.yml
- use new task file name to test if symlinks are broken. The symlink _seemed_ to work once, but now concourse is complaining the file looks wrong
-
-
None
> use new task file name to test if symlinks are broken

- broker/config.py
- broker/models.py
- broker/tasks/alb.py
- broker/tasks/huey.py
- tests/integration/test_server_setup.py
- make sure we call load_albs at least once during startup
None
> make sure we call load_albs at least once during startup

- broker/models.py
- log when we load albs
- tidier import organization
-
None
> log when we load albs

- broker/tasks/huey.py
- separate tasks 
- feed context to load_alb task
None
> separate tasks and feed context to load_alb task

- broker/app.py
- try loading albs at api startup instead
None
> try loading albs at api startup instead

- broker/app.py
- broker/tasks/cron.py
- broker/tasks/huey.py
- Load albs in a cron task
None
> Load albs in a cron task

- broker/models.py
- add an explicit commit to alb save
None
> add an explicit commit to alb save

- broker/config.py
- broker/tasks/alb.py
- broker/tasks/letsencrypt.py
- docker/tests
- pyproject.toml
- fix watch-tests config
- increase sleep time for ALB switches
None
> fix watch-tests config, increase sleep time for ALB switches

- broker/tasks/alb.py
- tests/integration/dedicated_alb/test_dedicated_alb_pick_listener.py
- fix empty result set condition when a dedicated alb has only deactivated service instances
-
-
None
> fix empty result set 

- broker/tasks/cron.py
- pick up dedicated alb tasks, too
None
> pick up dedicated alb tasks, too

- ci/pipeline.yml
- use a different org and space for tests
None
> use a different org and space for tests

- broker/duplicate_certs.py
- tests/integration/alb/test_alb_remove_duplicate_certs.py
- tests/integration/dedicated_alb/test_dedicated_alb_remove_duplicate_certs.py
- Fix listener ARNs input from config to `remove_duplicate_alb_certs`. `config.ALB_LISTENER_ARNS` and  `config.DEDICATED_ALB_LISTENER_ARNS` are already lists, so surrounding them with `[]` makes them a list of lists, which causes errors when passing these arguments as a `ListenerArn` to boto3 commands like [`describe_listener_certificates`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elbv2/client/describe_listener_certificates.html)
- Upgrade integration tests to tests for the above scenario to avoid regression
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be …
> Fix duplicate cert removal

- broker/config.py
- tests/integration/dedicated_alb/test_dedicated_alb_remove_duplicate_certs.py
- fix unit test for removing duplicate certificates for dedicated ALBs
None, just fixing unit test
> fix unit test for removing duplicate certificates for dedicated ALBs

- broker/tasks/waf.py
- tests/integration/test_waf.py
- fix tests for retries on deleting WAF web ACL to mock API calls the correct number of times
- update the delete web ACL code to retry 10 times before giving up 
- move file since it is an integration and not a unit test
None
> fix tests for retries on deleting WAF web ACL & move file

- ci/pipeline.yml
- remove secrets file from pipeline in favor of Credhub. Secrets for this pipeline configuration will now be read from Credhub
Credhub is one of our approved secret stores. This PR is a step towards improving consistency for all of our pipelines to store their secrets in Credhub.
> remove secrets file from pipeline in favor of Credhub

- acceptance/run.sh
- fix acceptance test script to set AWS_PAGER="" so that AWS CLI output prints straight to console without requiring "less" utility
None, should just be fixing acceptance tests
> fix acceptance test script

- broker/tasks/alb.py
- tests/integration/alb/test_alb_provisioning.py
- tests/lib/factories.py
- tests/lib/fake_alb.py
- tests/unit/test_alb.py
- Refactor logic for `get_lowest_dedicated_alb` into separate functions 
- Add unit tests
- Rename variables / add comments to clarify code behavior
None, just refactoring code for clarity
> Update dedicated ALB logic and add more unit tests

- broker/config.py
- broker/tasks/waf.py
- tests/integration/cdn_dedicated_waf/provision.py
- tests/lib/fake_wafv2.py
Related to https://github.com/cloud-gov/cg-provision/pull/1735
- Update web ACL creation logic to use a predictable name so that IAM permissions for managing these resources can be tightly scoped
These changes allow for more tightly scoped IAM permissions for creating/deleting WAF web ACLs. See …
> Update web ACL creation to use a predictable name

- ci/pipeline.yml
- Add acceptance tests for CDN with dedicated WAF plan
- Refactor pipeline to address YAML linter errors
None, just adding acceptance tests for a new broker feature
> Add acceptance tests for CDN with dedicated WAF lan

- broker/tasks/iam.py
- broker/tasks/route53.py
- tests/integration/cdn_dedicated_waf/provision.py
- tests/integration/cdn_dedicated_waf/update.py
- tests/integration/test_iam_idempotent.py
- tests/lib/fake_iam.py
- tests/lib/fake_route53.py
- Fix logic for setting caller reference name when creating Route53 health checks to respect length limit
- Add logic for handling case where IAM server certificate was already uploaded but not persisted to the database. Add integration test for this case …
> Fix more provision errors

- tests/lib/fake_iam.py
Related https://github.com/cloud-gov/private/issues/1098
- see title
None
> fix expected response structure for integration test

- broker/huey_consumer.py
- fix imports for huey_consumer based on https://github.com/cloud-gov/external-domain-broker/pull/358
None, just fixing broker imports
> fix imports for huey_consumer

- ci/pipeline.yml
- see title
None, just fixing typo in pipeline
> fix pipeline for registering CDN with dedicated WAF plan in production

- broker/tasks/cloudfront.py
- tests/integration/test_cloudfront.py
- tests/lib/fake_cloudfront.py
We are getting this error when our acceptance tests run in CI:
```shell
botocore.errorfactory.DistributionNotDisabled: An error occurred (DistributionNotDisabled) when calling the DeleteDistribution operation: The distribution you are trying to delete has not been disabled., 
```
This error doesn't cause the tests or service deletion to ultimately fail, because it just retries until the distribution has been fully disabled and deletes it. However, it would be preferable to have the task which is supposed to wait for a distribution to be disabled, `wait_for_distribution_disabled`, to correctly wait long enough so that this error does not occur.
[The problem is that we need to wait not only for the status of the distribution to be disabled, but also for that change to have fully deployed …
> Fix logic waiting for distribution to be disabled

- ci/pipeline.yml
- docker/Dockerfile.dev
- Reverts cloud-gov/external-domain-broker#359
There are issues with the hardened container pipeline for this image, so reverting changes for now
> Revert "Harden image"

- broker/aws.py
- update cloudwatch to create alarms in the correct region
None, just fixing broker behavior
> update cloudwatch to use global region

- broker/tasks/iam.py
- tests/lib/fake_iam.py
- only tag certs when we have tags to tag them with
None
> Fix: only tag certs when we have tags to tag them with

- broker/tasks/iam.py
- tests/lib/fake_iam.py
- use a substring check on error code, since we seem to be not matching right now
- log when our error code match fails, so we can see why we fail if this doesn't work
None
> Fix: looser error code checking and log codes when it fails

- broker/tasks/iam.py
- tests/conftest.py
- tests/integration/alb/test_alb_renewals.py
- tests/integration/cdn/test_cdn_renewals.py
- tests/integration/dedicated_alb/test_dedicated_alb_renewals.py
- tests/integration/test_cloudfront.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_iam_idempotent.py
- tests/integration/test_route53.py
- tests/integration/test_shield.py
- tests/integration/test_waf.py
- tests/lib/fake_iam.py
- tests/lib/identifiers.py
- tests/lib/update.py
- Refactor logic for deleting server certificates to check if they exist first, then only attempt deletion if the certificate does exist
- Moved common test fixtures for identifiers to shared lib
- Update `expect_get_server_certificate` on fake IAM service to use dummy values for cert and chain, which makes testing much less cumbersome
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional …
> Refactor code

- docker/Dockerfile.dev
- Installs awscli through python rather than ubuntu package
Fixing acceptance tests by installing awscli using python
> update image to install awscli through python

- ci/pipeline.yml
- Updates the time resource to use the hardened image
Last image that needs to be updated for this pipeline
> update time resource to use hardened image

- broker/tasks/route53.py
- tests/conftest.py
- tests/integration/alb/test_alb_renewals.py
- tests/integration/alb/test_alb_update.py
- tests/integration/dedicated_alb/test_dedicated_alb_renewals.py
- tests/integration/dedicated_alb/test_dedicated_alb_update.py
- tests/integration/plan_updates/test_alb_update_to_dedicated_alb.py
- tests/integration/plan_updates/test_migration_update_to_alb.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_route53.py
- tests/integration/test_shield.py
- tests/integration/test_waf.py
- tests/lib/alb/update.py
- tests/lib/cdn/instances.py
- Fix error observed in logs during `create_health_checks` task when upgrading CDN to CDN with dedicated WAF instances
- Fix other integration test failures
None, just fixing bugs
> Fix route53 create health check behavior on instance type update

- broker/pipelines/cdn_dedicated_waf.py
- broker/pipelines/plan_updates.py
- broker/tasks/cloudwatch.py
- broker/tasks/route53.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_provisioning.py
- tests/integration/plan_updates/test_cdn_update_to_cdn_dedicated_waf.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_route53.py
- [delete route53.create_health_checks method and replace with route53.create_new_health_checks & refactor tests](https://github.com/cloud-gov/external-domain-broker/commit/48a26aced57ff69e6412818fc32cf9aa8b970267) 
- [update update_health_check_alarms to handle missing cloudwatch_health_check_alarms property on service instance](https://github.com/cloud-gov/external-domain-broker/commit/1d8694d786fb4d31f99563792160406a35c00771) 
- [add test for update_health_check_alarms idempotency](https://github.com/cloud-gov/external-domain-broker/commit/63c9f38bb0f1c70f30af06bbb444e9a8e8249f0c)
- Are log statements using a logging library with a logging level set? Setting a logging level means that log …
> Fix idempotency

- broker/api.py
- broker/lib/cdn.py
- broker/models.py
- broker/tasks/cloudwatch.py
- broker/tasks/cron.py
- broker/tasks/huey.py
- dev
- tests/conftest.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_renewals.py
- tests/integration/plan_updates/test_cdn_update_to_cdn_dedicated_waf.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_cron.py
- tests/lib/cdn/instances.py
- Add missing code for restarting stalled pipelines for CDN with dedicated WAF instances
- Update code to use enum for service instance types 
- Catch `IndexError` when restarting operations
- Add integration test for CDN with dedicated WAF renewals
None, …
> Add cron pipelines dedicated WAF

- broker/config.py
- broker/tasks/cloudfront.py
- broker/tasks/cloudwatch.py
- broker/tasks/cron.py
- broker/tasks/route53.py
- broker/tasks/shield.py
- broker/tasks/waf.py
- tests/integration/test_cloudfront.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_cron.py
- tests/integration/test_route53.py
- tests/integration/test_shield.py
- tests/integration/test_waf.py
- tests/lib/cdn/instances.py
- Make retry logic for `wait_for_distribution_disabled` consistent with other code
- update `disassociate_health_check` to handle instance with missing columns
- update `delete_web_acl` to handle instances with missing columns
- update `delete_health_checks` to handle missing columns
None, just fixing broker bugs
> Various fixes

- broker/tasks/cloudwatch.py
- broker/tasks/shield.py
- broker/tasks/waf.py
- tests/integration/test_cloudwatch.py
- tests/integration/test_route53.py
- tests/integration/test_shield.py
- tests/integration/test_waf.py
- Update various delete tasks to ensure they handle empty values for the relevant columns correctly
- Add/update tests as necessary to ensure that tasks handle empty values correctly
None, just fixing broker bugs
> Update delete tasks to handle empty values

- broker/tasks/iam.py
- tests/integration/alb/test_alb_deprovisioning.py
- tests/integration/cdn/test_cdn_deprovisioning.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_deprovisioning.py
- tests/integration/dedicated_alb/test_dedicated_alb_deprovisioning.py
- tests/integration/test_iam_idempotent.py
- tests/lib/alb/deprovision.py
- tests/lib/cdn/deprovision.py
- tests/lib/deprovision.py
- tests/lib/fake_iam.py
- Add logic to check for certificate before attempting deletion. Skip deletion if certificate does not exist
- Refactor tests to use shared helpers 
- Add more tests for IAM delete certificate idempotency
- Update IAM idempotency tests to use parameters for all service instance types
None, just improving IAM …
> Update delete certificate logic

- broker/pipelines/alb.py
- broker/pipelines/cdn.py
- broker/pipelines/cdn_dedicated_waf.py
- broker/pipelines/dedicated_alb.py
- broker/tasks/route53.py
- tests/integration/alb/test_alb_order_status_mismatch.py
- tests/integration/alb/test_alb_provisioning.py
- tests/integration/alb/test_alb_update.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_deprovisioning.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_provisioning.py
- tests/integration/dedicated_alb/test_dedicated_alb_provisioning.py
- tests/integration/dedicated_alb/test_dedicated_alb_renewals.py
- tests/integration/dedicated_alb/test_dedicated_alb_update.py
- tests/integration/plan_updates/test_alb_update_to_dedicated_alb.py
- tests/integration/plan_updates/test_cdn_update_to_cdn_dedicated_waf.py
- tests/integration/test_route53.py
- tests/lib/alb/update.py
- tests/lib/cdn/update.py
- tests/lib/update.py
Fixes https://github.com/cloud-gov/external-domain-broker/issues/291
- Add `route53.remove_old_DNS_records` to remove TXT/ALIAS records in Route53 for domain names that are no longer active during an update operation
- Add `route53.remove_old_DNS_records` step to update pipelines for all service instances
- Add integration tests for `route53.remove_old_DNS_records` task
- Add step to integration tests of service update pipelines for `route53.remove_old_DNS_records`
- Clean up duplicate fixture declarations
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the …
> Remove old DNS records on update

- acceptance/run.sh
- see title
None, just fixing typo
> fix typo in acceptance tests run script

- broker/pipelines/cdn_dedicated_waf.py
- tests/integration/cdn_dedicated_waf/deprovision.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_provisioning.py
- tests/integration/cdn_dedicated_waf/update.py
- To ensure that the SNS email subscription is changed to the updated email anytime the service is updated, add a step for `unsubscribe_notification_topic` before `subscribe_notification_topic` in the update pipeline for CDN dedicated WAF instances
None, just updating broker behavior
> add unsubscribe step to update pipeline for CDN with dedicated WAF

- broker/tasks/sns.py
- ci/pipeline.yml
- tests/integration/tasks/test_sns.py
- tests/lib/fake_sns.py
- Update `unsubscribe_notification_topic` to not throw error if the subscription is still pending confirmation and cannot be unsubscribed. This will fix failing integration tests where the subscription is never actually confirmed while the tests are running
None, just fixing broker behavior
> Handle unsubscribe pending confirmation

- tests/unit/test_config.py
- see title
None, just fixing unit tests
> add missing env var for config unit tests

- pip-tools/requirements.in
- pyproject.toml
We have upgraded to `cryptography > 43` because `pyca/cryptography` has vulnerabilities for >= 37.0.0, < 43.0.1
To upgrade `cryptography`, we had to update `pyopenssl`, since [pyopenssl doesn't support cryptography > 43 until version 24.2.0](https://github.com/pyca/pyopenssl/blob/24.2.1/setup.py#L96).
However, [pyopenssl 24.2.0 deprecates X509Req](https://github.com/certbot/josepy/issues/181), which leads to these errors:
```
DeprecationWarning: CSR support in pyOpenSSL is deprecated. You should use the APIs in cryptography.
```
This issue is noted in https://github.com/certbot/josepy/issues/181 and discussed in https://github.com/certbot/josepy/issues/182.
Unfortunately, there is no clear fix for this issue right now. The maintainers of josepy are considering abandoning it for a new …
> ignore deprecation warnings from updated packages

- broker/tasks/cloudfront.py
- migrations/versions/8cb1ecea6207_add_all_initial_tables.py
- tests/integration/alb/test_alb_check_duplicate_certs.py
- tests/integration/cdn/test_cdn_updates.py
- tests/integration/dedicated_alb/test_dedicated_alb_check_duplicate_certs.py
- tests/lib/fake_cloudfront.py
- allow updating instances that reference cache policy ids
None - this doesn't change the security posture of this app or the instances it touches.
> allow updating instances that reference cache policy ids

- broker/tasks/cloudfront.py
- tests/integration/cdn/test_cdn_updates.py
Addresses #405 
Follow-up to #407 
It turns out that the default value for `forwarded_headers` on CDNs is `["HOST"]`: https://github.com/cloud-gov/external-domain-broker/blob/main/broker/api.py#L462
So for cases of CDNs that may have a custom `CachePolicyId`, but have `forwarded_headers: ["HOST"]`, we need to update the checks so that their updates can go through and continue using a custom cache policy.
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then …
> update check for default forwarded headers to expect HOST

- broker/tasks/shield.py
- tests/integration/tasks/test_shield.py
- update update_associated_health_check task to handle case where no associated health check yet exists
None, just fixing a bug in the task logic
> update update_associated_health_check task logic

- broker/lib/tags.py
- broker/models.py
- broker/tasks/cloudfront.py
- tests/conftest.py
- tests/integration/cdn/test_cdn_updates.py
- tests/integration/tasks/test_cloudfront.py
- tests/lib/cdn/update.py
- tests/lib/fake_cloudfront.py
- tests/lib/identifiers.py
- tests/unit/test_tags.py
The `update_distribution` logic was not updating CDN with dedicated WAF instances with the correct tags nor applying the dedicated WAF web ACL to the CDN itself. This PR fixes both of those issues and adds the relevant tests for the updated behaviors.
The changes in the PR themselves have no security impact as they …
> Fix CDN update distribution logic

- broker/config.py
- broker/lib/cache_policy_manager.py
- broker/lib/cdn.py
- broker/lib/origin_request_policy_manager.py
- tests/integration/api/test_cdn_provision_common_checks.py
- tests/integration/api/test_cdn_update_common_checks.py
- tests/integration/tasks/test_cloudfront.py
- tests/lib/fake_cloudfront.py
- tests/unit/test_cache_policy_manager.py
- tests/unit/test_cdn.py
- tests/unit/test_origin_request_policy_manager.py
When running the acceptance tests from #420 in staging, we are seeing this error:
```
KeyError: 'CachingDisabled'
```
Further investigation revealed that for [a policy name of `CachingDisabled` as mentioned in the AWS documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html), the actual policy name returned by the CloudFront ListCachePolicies API is `Managed-CachingDisabled`. Since the broker was caching the policies from in AWS in a hash keyed by the policy name in the API response, `CachingDisabled` was not found and hence the `KeyError`. 
The easiest solution is to have the broker expect as input the names of the policies as returned by the CloudFront API. I will make sure to document these values on the external-domain-broker …
> Fix policy handling

- acceptance/run.sh
Part of https://github.com/cloud-gov/external-domain-broker/issues/412
- update parameters for cache policy and origin request policy in acceptance test creating a CDN with dedicated WAF instance to match expected values for broker that were changed in #421  
None. The code changes are no sensitive
> update parameters for acceptance tests

- acceptance/run.sh
- broker/tasks/cloudfront.py
- tests/lib/fake_cloudfront.py
The acceptance tests to create a CDN with dedicated WAF service instance using a managed cache policy and managed origin request policy are failing with
```
The parameter MinTTL cannot be used when a cache policy is associated to the cache behavior
```
Upon reviewing the [relevant AWS documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DefaultCacheBehavior.html), it seems like the `MinTTL`, `MaxTTL`, and `DefaultTTL` properties are deprecated when you are supply a cache policy. 
So this PR updates the CDN provisioning logic to unset those properties when a `CachePolicyId` is supplied.
The PR also updates the acceptance test to use the `Managed-CachingOptimized` cache policy.
- For any logging statements, is there any chance that they could be logging sensitive …
> Fix apply cache policy logic

- broker/tasks/cloudfront.py
- tests/integration/tasks/test_cloudfront.py
- tests/lib/fake_cloudfront.py
- [fix update_default_cache_behavior() to preserve managed cache policy and managed origin request policyfrom existing distribution config, even if no updates are specified to these values](https://github.com/cloud-gov/external-domain-broker/commit/bec2a8220d969f64ddf375f9e0a8ab3001d3feb7) 
- [add unit test to confirm that CDN updates preserve existing CDN configuration](https://github.com/cloud-gov/external-domain-broker/commit/90571fdfb4850991e47146f8f89bd38b77bd2825) 
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and …
> Fix update CDN policy logic to preserve existing values

- broker/app.py
- broker/commands/tags.py
- broker/commands/waf.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_deprovisioning.py
- tests/integration/commands/test_tags.py
- tests/integration/commands/test_waf.py
- tests/integration/tasks/test_waf.py
- tests/lib/fake_wafv2.py
- Update `add_dedicated_alb_waf_web_acls` to wait for web ACL creation to finish before attempting to associate it
- Add `add_dedicated_alb_tags` command to set tags on web ACLs
- Add/update tests for new behaviors
None. The code changes are not sensitive
> Wait for web ACL on creation before associating

- broker/app.py
- broker/commands/waf.py
- broker/tasks/waf.py
- tests/integration/cdn_dedicated_waf/test_cdn_dedicated_waf_deprovisioning.py
- tests/integration/commands/test_waf.py
- tests/integration/tasks/test_waf.py
- tests/lib/fake_wafv2.py
Follow-up to #442. When updating a dedicated org load balancer to **one WAF web ACL to be shared by all load balancers for an organization, rather than one WAF web ACL for each of the load balancers**, we need to clean up the old WAF web ACL that was shared by all the load balancers.
This PR implements the logic to delete the obsolete WAF web ACL once the new one is associated.
- Rename `associate-dedicated-alb-waf-web-acls` to `update-dedicated-alb-waf-web-acls`
- Update logic for `update-dedicated-alb-waf-web-acls` to:
- Associate new web ACL tracked by database only if it is not already associated with the ALB
- Wait to confirm that new web ACL has been associated with ALB
- Delete the obsolete web ACL no longer associated with the ALB
- Update tests for new behavior
- For any logging …
> Update associate WAF web ACL logic

- broker/commands/waf.py
- broker/config.py
- broker/tasks/waf.py
- pip-tools/requirements.in
- requirements.txt
- tests/integration/commands/test_waf.py
- tests/lib/fake_wafv2.py
- tests/unit/test_config.py
- [update update_dedicated_alb_web_acl_info to use list_web_acls to find already provisioned web ACL](https://github.com/cloud-gov/external-domain-broker/commit/2dcce40f0d8bfd5a502ef7e05e3351df3e464212) 
- [add types-boto3 and types-boto3[wafv2] packages for type hinting](https://github.com/cloud-gov/external-domain-broker/commit/129794239fd88e90ce7a45bbcb6e677ecf597261)
- [improve type hinting of config values](https://github.com/cloud-gov/external-domain-broker/commit/b9c62bf99083a0cde3fb61a5671ba74a01073e59)
- update tests
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. …
> Fix command to create WAF web ACLs for dedicated ALBs

- broker/commands/waf.py
- update update_dedicated_alb_waf_web_acls to skip dedicated ALB if correct WAF is already associated, not return
-
-
None, just fixing behavior of the update web ACL command logic
> Fix update web ACL command logic
